// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb_ram_dma_fill.h for the primary calling header

#ifndef VERILATED_VTB_RAM_DMA_FILL___024ROOT_H_
#define VERILATED_VTB_RAM_DMA_FILL___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vtb_ram_dma_fill__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb_ram_dma_fill___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ tb_ram_dma_fill__DOT__clk;
        CData/*0:0*/ tb_ram_dma_fill__DOT__reset;
        CData/*0:0*/ tb_ram_dma_fill__DOT__clk_cpu;
        CData/*0:0*/ tb_ram_dma_fill__DOT__cpu_ce_posedge;
        CData/*0:0*/ tb_ram_dma_fill__DOT__cpu_ce_negedge;
        CData/*1:0*/ tb_ram_dma_fill__DOT__ram_rd_wait;
        CData/*0:0*/ tb_ram_dma_fill__DOT__dmac_cs_n;
        CData/*0:0*/ tb_ram_dma_fill__DOT__bench_iow_n;
        CData/*3:0*/ tb_ram_dma_fill__DOT__bench_adr;
        CData/*7:0*/ tb_ram_dma_fill__DOT__bench_dw;
        CData/*0:0*/ tb_ram_dma_fill__DOT__bench_memrd_n;
        CData/*0:0*/ tb_ram_dma_fill__DOT__dmac_ior_out_n;
        CData/*0:0*/ tb_ram_dma_fill__DOT__dmac_iow_out_n;
        CData/*0:0*/ tb_ram_dma_fill__DOT__dmac_memrd_n;
        CData/*0:0*/ tb_ram_dma_fill__DOT__dmac_memwr_n;
        CData/*3:0*/ tb_ram_dma_fill__DOT__dack_n;
        CData/*0:0*/ tb_ram_dma_fill__DOT__hrq;
        CData/*0:0*/ tb_ram_dma_fill__DOT__ab_io_write_n;
        CData/*0:0*/ tb_ram_dma_fill__DOT__clip_active;
        CData/*0:0*/ tb_ram_dma_fill__DOT__hlda;
        CData/*0:0*/ tb_ram_dma_fill__DOT__aen_n;
        CData/*0:0*/ tb_ram_dma_fill__DOT__dma_wait;
        CData/*0:0*/ tb_ram_dma_fill__DOT__want_drq;
        CData/*0:0*/ tb_ram_dma_fill__DOT__p1_flag;
        CData/*3:0*/ tb_ram_dma_fill__DOT__dreq;
        CData/*0:0*/ tb_ram_dma_fill__DOT__dma_ready;
        CData/*0:0*/ tb_ram_dma_fill__DOT__memory_access_ready;
        CData/*0:0*/ tb_ram_dma_fill__DOT__gv_req;
        CData/*0:0*/ tb_ram_dma_fill__DOT__ri_req;
        CData/*0:0*/ tb_ram_dma_fill__DOT__fgn_rd;
        CData/*1:0*/ tb_ram_dma_fill__DOT__s_ba;
        CData/*0:0*/ tb_ram_dma_fill__DOT__s_cke;
        CData/*0:0*/ tb_ram_dma_fill__DOT__s_dq_io;
        CData/*0:0*/ tb_ram_dma_fill__DOT__s_ldqm;
        CData/*0:0*/ tb_ram_dma_fill__DOT__s_udqm;
        CData/*0:0*/ tb_ram_dma_fill__DOT__all_mem_rd_n;
        CData/*1:0*/ tb_ram_dma_fill__DOT____Vcellinp__sdr__dqm;
        CData/*0:0*/ tb_ram_dma_fill__DOT__dmac_memwr_d;
        CData/*7:0*/ tb_ram_dma_fill__DOT__unnamedblk1__DOT__got;
        CData/*1:0*/ tb_ram_dma_fill__DOT__u_ce__DOT__active_clk_select;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ce__DOT__speed_change;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__lock_bus_control;
        CData/*7:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__internal_data_bus;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__write_command_register;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__write_mode_register;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__write_request_register;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__set_or_reset_mask_register;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__write_mask_register;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__write_base_and_current_address;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__write_base_and_current_word_count;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__master_clear;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__clear_mask_register;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__read_current_address;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__read_current_word_count;
        CData/*1:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__dma_rotate;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__edge_request;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__dma_request_state;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__encoded_dma;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__end_of_process_internal;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__autoinit_enable;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__dma_acknowledge_internal;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__transfer_register_select;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__initialize_current_register;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__next_word;
    };
    struct {
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Bus_Control_Logic__DOT__prev_write_enable_n;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Bus_Control_Logic__DOT__write_flag;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Bus_Control_Logic__DOT__stable_address;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Bus_Control_Logic__DOT__read_flag;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Priority_Encoder__DOT__controller_disable;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Priority_Encoder__DOT__rotating_priority;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Priority_Encoder__DOT__dreq_sense_active_low;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Priority_Encoder__DOT__mask_register;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Priority_Encoder__DOT__request_register;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Priority_Encoder__DOT__dma_request_ff;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Priority_Encoder__DOT__dma_request_lock;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Address_And_Count_Registers__DOT__prev_read_current_address;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Address_And_Count_Registers__DOT__prev_read_current_word_count;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Address_And_Count_Registers__DOT__byte_pointer;
        CData/*1:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Address_And_Count_Registers__DOT__dma_select;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Timing_And_Control__DOT__next_s4;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Timing_And_Control__DOT__chanel_0_address_hold_enable;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Timing_And_Control__DOT__compressed_timing;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Timing_And_Control__DOT__extended_write_selection;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Timing_And_Control__DOT__dack_sense_active_high;
        CData/*1:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Timing_And_Control__DOT__dma_select;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Timing_And_Control__DOT__dma_acknowledge_ff;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Timing_And_Control__DOT__terminal_count;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Timing_And_Control__DOT__reoutput_high_address;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Timing_And_Control__DOT__external_end_of_process;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ready__DOT__prev_bus_state;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ready__DOT__ready_n_or_wait;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ready__DOT__ready_n_or_wait_Qn;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ready__DOT__prev_ready_n_or_wait;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ready__DOT__bus_state;
        CData/*7:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__latch_data;
        CData/*7:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__latch_data_hi;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__write_command;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__read_command;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__wc_pend;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__wc_pend2;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__accept_live_wr;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__accept_live_rd;
        CData/*7:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__pend_data;
        CData/*7:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__pend_data_hi;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__pend_word;
        CData/*7:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__pend2_data;
        CData/*7:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__pend2_data_hi;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__pend2_word;
        CData/*7:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__accept_data;
        CData/*7:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__accept_data_hi;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__accept_word;
        CData/*1:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__read_wait_count;
        CData/*1:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__write_wait_count;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__vram_rd_wait_count;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__vram_wr_wait_count;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__write_request;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__read_request;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__write_flag;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__read_flag;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__new_write_strobe;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__new_write_strobe2;
        CData/*7:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__data_bus_out_reg;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__write_command_d;
        CData/*7:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__dbg_blocked;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__dbg_drop_wr;
        CData/*2:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__dbg_drop_st;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__write_strobe_fell;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT____VdfgTmp_heded080f__0;
    };
    struct {
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT____VdfgTmp_hf0bd275d__0;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT____VdfgTmp_h6a00c20b__0;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__req;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__we_r;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__busy;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__len_r;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__rbeat;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__mp_rvalid;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__init_done;
        CData/*4:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__mp_req;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__mp_wcnt;
        CData/*4:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__mp_ack;
        CData/*4:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__mp_done;
        CData/*2:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__mp_grant;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__state;
        CData/*2:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__cmd;
        CData/*2:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__rr_ptr;
        CData/*2:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__winner;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__have_req;
        CData/*4:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__left;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__cur_we;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__refresh_due;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__rd_pipe;
        CData/*1:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__act_bank;
        CData/*1:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__cur_bank;
        CData/*3:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__row_open;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__row_miss;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT____Vlvbound_h53139d90__0;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT____Vlvbound_h7fb74084__0;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT____Vlvbound_h7fb74084__1;
        CData/*0:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT____VdfgTmp_h1ea43d0e__0;
        CData/*0:0*/ tb_ram_dma_fill__DOT__sdr__DOT__hold1;
        CData/*0:0*/ tb_ram_dma_fill__DOT__sdr__DOT__hold2;
        CData/*0:0*/ tb_ram_dma_fill__DOT__sdr__DOT____VdfgTmp_h854dc19a__0;
        CData/*3:0*/ __Vfunc_rotate_right__12__Vfuncout;
        CData/*3:0*/ __Vfunc_rotate_right__12__source;
        CData/*1:0*/ __Vfunc_rotate_right__12__rotate;
        CData/*3:0*/ __Vfunc_rotate_left__14__Vfuncout;
        CData/*3:0*/ __Vfunc_rotate_left__14__source;
        CData/*1:0*/ __Vfunc_rotate_left__14__rotate;
        CData/*0:0*/ __Vfunc_tb_ram_dma_fill__DOT__u_ram__DOT__pc98_sdram_hits__17__Vfuncout;
        CData/*3:0*/ __Vdly__tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__state;
        CData/*3:0*/ __Vdly__tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__mp_wcnt;
        CData/*2:0*/ __Vdly__tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__mp_grant;
        CData/*3:0*/ __Vdly__tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__rd_pipe;
        CData/*4:0*/ __Vdly__tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__left;
        CData/*0:0*/ __Vdly__tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__cur_we;
        CData/*0:0*/ __Vdlyvset__tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__open_row__v0;
        CData/*0:0*/ __Vdlyvset__tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__open_row__v1;
        CData/*0:0*/ __Vdly__tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__we_r;
        CData/*3:0*/ __Vdly__tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__len_r;
        CData/*0:0*/ __VstlDidInit;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_ram_dma_fill__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_ram_dma_fill__DOT__reset__0;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        SData/*15:0*/ tb_ram_dma_fill__DOT__dmac_addr_out;
        SData/*12:0*/ tb_ram_dma_fill__DOT__s_a;
        SData/*15:0*/ tb_ram_dma_fill__DOT__s_dq_out;
        SData/*15:0*/ tb_ram_dma_fill__DOT__dq_in__en0;
        SData/*8:0*/ tb_ram_dma_fill__DOT__u_ce__DOT__cpu_phase_acc;
        SData/*8:0*/ tb_ram_dma_fill__DOT__u_ce__DOT__cpu_edge_num;
        SData/*8:0*/ tb_ram_dma_fill__DOT__u_ce__DOT__cpu_edge_den;
    };
    struct {
        SData/*9:0*/ tb_ram_dma_fill__DOT__u_ce__DOT__cpu_phase_sum;
        SData/*15:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Address_And_Count_Registers__DOT__temporary_address;
        SData/*9:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__access_num;
        SData/*15:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__access_data_in;
        SData/*15:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__access_data_in_hi;
        SData/*15:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__access_data_out;
        SData/*15:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__dbg_parks;
        SData/*15:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__dbg_drops;
        SData/*15:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__wdata_r;
        SData/*15:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__wdata_hi_r;
        SData/*15:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__mp_rdata;
        VlWide<3>/*79:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__mp_wdata;
        SData/*8:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__cur_col;
        SData/*15:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__timer;
        SData/*15:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__init_left;
        SData/*15:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__refresh_cnt;
        SData/*12:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__act_row;
        SData/*15:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__pre_guard;
        SData/*12:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT____VdfgTmp_h44e2fdf7__0;
        SData/*15:0*/ tb_ram_dma_fill__DOT__sdr__DOT__unnamedblk8__DOT__cur;
        SData/*15:0*/ __Vdly__tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__timer;
        SData/*15:0*/ __Vdly__tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__init_left;
        SData/*15:0*/ __Vdly__tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__refresh_cnt;
        SData/*8:0*/ __Vdly__tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__cur_col;
        SData/*15:0*/ __Vdly__tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__pre_guard;
        SData/*8:0*/ __Vtrigprevexpr___TOP__tb_ram_dma_fill__DOT__u_ce__DOT__cpu_edge_num__0;
        SData/*8:0*/ __Vtrigprevexpr___TOP__tb_ram_dma_fill__DOT__u_ce__DOT__cpu_edge_num__1;
        IData/*19:0*/ tb_ram_dma_fill__DOT__bench_addr;
        IData/*31:0*/ tb_ram_dma_fill__DOT__clipw;
        IData/*31:0*/ tb_ram_dma_fill__DOT__clip_cnt;
        IData/*31:0*/ tb_ram_dma_fill__DOT__p1_at;
        IData/*31:0*/ tb_ram_dma_fill__DOT__p1_len;
        IData/*31:0*/ tb_ram_dma_fill__DOT__p1_tick;
        IData/*19:0*/ tb_ram_dma_fill__DOT__bus_addr;
        IData/*31:0*/ tb_ram_dma_fill__DOT__gv_timer;
        IData/*23:0*/ tb_ram_dma_fill__DOT__ri_addr;
        IData/*31:0*/ tb_ram_dma_fill__DOT__fgn_timer;
        IData/*31:0*/ tb_ram_dma_fill__DOT__memw_pulses;
        IData/*31:0*/ tb_ram_dma_fill__DOT__wc_seen;
        IData/*31:0*/ tb_ram_dma_fill__DOT__wr_accept;
        IData/*31:0*/ tb_ram_dma_fill__DOT__sdr_writes;
        IData/*31:0*/ tb_ram_dma_fill__DOT__tail_trace;
        IData/*23:0*/ tb_ram_dma_fill__DOT__acc_prev;
        IData/*31:0*/ tb_ram_dma_fill__DOT__errors;
        IData/*16:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Address_And_Count_Registers__DOT__temporary_word_count;
        IData/*31:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Timing_And_Control__DOT__state;
        IData/*31:0*/ tb_ram_dma_fill__DOT__u_dmac__DOT__u_Timing_And_Control__DOT__next_state;
        IData/*31:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__state;
        IData/*31:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__next_state;
        IData/*23:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__latch_address;
        IData/*23:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__pend_address;
        IData/*23:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__pend2_address;
        IData/*23:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__accept_address;
        IData/*24:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__access_address;
        IData/*23:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__dbg_drop_addr;
        IData/*23:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__addr_r;
        VlWide<4>/*119:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__mp_addr;
        IData/*23:0*/ tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__cur_addr;
        IData/*31:0*/ tb_ram_dma_fill__DOT__sdr__DOT__dbg_rd;
        IData/*31:0*/ tb_ram_dma_fill__DOT__sdr__DOT__ref_at;
        IData/*31:0*/ tb_ram_dma_fill__DOT__sdr__DOT__ref_count;
        IData/*31:0*/ tb_ram_dma_fill__DOT__sdr__DOT__cyc;
        IData/*31:0*/ tb_ram_dma_fill__DOT__sdr__DOT__cas_lat;
        IData/*31:0*/ tb_ram_dma_fill__DOT__sdr__DOT__violations;
    };
    struct {
        IData/*31:0*/ tb_ram_dma_fill__DOT__sdr__DOT__reads_served;
        IData/*31:0*/ tb_ram_dma_fill__DOT__sdr__DOT__writes_served;
        IData/*31:0*/ tb_ram_dma_fill__DOT__sdr__DOT__unnamedblk7__DOT__addr;
        IData/*31:0*/ tb_ram_dma_fill__DOT__sdr__DOT__unnamedblk8__DOT__addr;
        IData/*19:0*/ __Vfunc_tb_ram_dma_fill__DOT__u_ram__DOT__pc98_sdram_hits__17__a;
        IData/*23:0*/ __Vdly__tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__cur_addr;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<SData/*10:0*/, 4> tb_ram_dma_fill__DOT__ems98_unused;
        VlUnpacked<CData/*1:0*/, 4> tb_ram_dma_fill__DOT__u_dmac__DOT__u_Priority_Encoder__DOT__bit_select;
        VlUnpacked<SData/*15:0*/, 4> tb_ram_dma_fill__DOT__u_dmac__DOT__u_Address_And_Count_Registers__DOT__base_address;
        VlUnpacked<SData/*15:0*/, 4> tb_ram_dma_fill__DOT__u_dmac__DOT__u_Address_And_Count_Registers__DOT__current_address;
        VlUnpacked<SData/*15:0*/, 4> tb_ram_dma_fill__DOT__u_dmac__DOT__u_Address_And_Count_Registers__DOT__base_word_count;
        VlUnpacked<SData/*15:0*/, 4> tb_ram_dma_fill__DOT__u_dmac__DOT__u_Address_And_Count_Registers__DOT__current_word_count;
        VlUnpacked<CData/*1:0*/, 4> tb_ram_dma_fill__DOT__u_dmac__DOT__u_Timing_And_Control__DOT__bit_select;
        VlUnpacked<CData/*1:0*/, 4> tb_ram_dma_fill__DOT__u_dmac__DOT__u_Timing_And_Control__DOT__transfer_type;
        VlUnpacked<CData/*0:0*/, 4> tb_ram_dma_fill__DOT__u_dmac__DOT__u_Timing_And_Control__DOT__autoinitialization_enable;
        VlUnpacked<CData/*0:0*/, 4> tb_ram_dma_fill__DOT__u_dmac__DOT__u_Timing_And_Control__DOT__address_decrement_select;
        VlUnpacked<CData/*1:0*/, 4> tb_ram_dma_fill__DOT__u_dmac__DOT__u_Timing_And_Control__DOT__transfer_mode;
        VlUnpacked<SData/*12:0*/, 4> tb_ram_dma_fill__DOT__u_ram__DOT__u_sdram__DOT__u_mp__DOT__open_row;
        VlUnpacked<IData/*31:0*/, 4> tb_ram_dma_fill__DOT__sdr__DOT__open_row;
        VlUnpacked<IData/*31:0*/, 4> tb_ram_dma_fill__DOT__sdr__DOT__act_at;
        VlUnpacked<IData/*31:0*/, 4> tb_ram_dma_fill__DOT__sdr__DOT__pre_at;
        VlUnpacked<IData/*31:0*/, 4> tb_ram_dma_fill__DOT__sdr__DOT__wr_at;
        VlUnpacked<SData/*15:0*/, 6> tb_ram_dma_fill__DOT__sdr__DOT__rd_data;
        VlUnpacked<CData/*0:0*/, 6> tb_ram_dma_fill__DOT__sdr__DOT__rd_vld;
    };
    VlAssocArray<IData/*31:0*/, SData/*15:0*/> tb_ram_dma_fill__DOT__sdr__DOT__store;
    VlDelayScheduler __VdlySched;
    VlTriggerScheduler __VtrigSched_hff9fd67f__0;
    VlTriggerVec<2> __VstlTriggered;
    VlTriggerVec<5> __VactTriggered;
    VlTriggerVec<5> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtb_ram_dma_fill__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtb_ram_dma_fill___024root(Vtb_ram_dma_fill__Syms* symsp, const char* v__name);
    ~Vtb_ram_dma_fill___024root();
    VL_UNCOPYABLE(Vtb_ram_dma_fill___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
