//
// pc98_opna -- the PC-9801-86 sound board's YM2608 (OPNA) at 0x188-0x18F.
//
// WHAT THIS IS. Four I/O ports and a register router. The synthesis itself is
// jotego's jt12_top, parameterised as an OPNA: num_ch=6, use_ssg=1, use_lfo=1,
// use_pcm=0, use_adpcm=1. Measured standalone on the 5CEBA4 with
// scripts/measure_core.sh, that configuration is 1334 ALM / 1946 regs /
// 8003 block-RAM bits -- against a free budget of about 1806 ALM once the IDE
// block (216.6 ALM) was gated out of the PC-98 build. jt03 (the YM2203 on the
// -26K board) would have been 854 and jt10 (YM2610) 1674.
//
// THE PORTS. np2kai cbus/board86.c:171 binds the board with
//   cbuscore_attachsndex(0x188 + g_opna[0].s.base, opna_o, opna_i)
// and s.base is 0 for the default dip setting, so:
//   0x188  W: latch part-0 register index       R: status 0 {busy,0,..,flagB,flagA}
//   0x18A  W: write the latched part-0 register R: SSG read-back / data latch
//   0x18C  W: latch part-1 register index       R: status 1 {EOS,BRDY,rhythm[5:0]}
//   0x18E  W: write the latched part-1 register R: ADPCM read-back / data latch
// The 0x18C/0x18E pair only answers when the board is in "extended" mode, and
// extended mode is NOT a YM2608 register: np2kai cbus/pcm86io.c:45-51 sets it
// from bit 0 of a write to 0xA460 (pcm86_oa460 -> fmboard_extenable), which
// board86.c:114 wires to opngen_setcfg(6 channels, stereo) vs (3, mono).
// That is why ext_enable comes in from outside.
//
// THE CLOCK. np2kai sound/opngen.h:13 has OPNA_CLOCK = 3993600 and
// sound/opna.c:123 initialises fmgen at OPNA_CLOCK*2, so the chip clock is
// 7.9872 MHz. clk here is clk_chipset at 42.954545 MHz, so cen is generated by
// a 16-bit fractional accumulator with INC = round(7.9872/42.954545 * 65536)
// = 12185, which lands on 7.987005 MHz, -0.0024%. jt12_div then does the
// YM2608 prescaler (/6 FM, /4 SSG at reset) internally -- see its own comment
// block, which is written against the YM2608 datasheet.
//
// THE ROUTER, AND WHY THERE IS ONE. jt12's ADPCM register map is the YM2610's,
// not the YM2608's, and the two chips have their ADPCM halves on opposite
// sides of the A1 address bit:
//
//   guest (YM2608)                      jt12 (YM2610)
//   part 0  0x00-0x0F  SSG              part 0  0x00-0x0F  SSG
//   part 0  0x10-0x1D  RHYTHM           part 0  0x10-0x1C  ADPCM-B
//   part 0  0x20-0xFF  timers, FM 1-3   part 0  0x20-0xFF  timers, FM 1-3
//   part 1  0x00-0x10  ADPCM-B/DELTA-T  part 1  0x00-0x2D  ADPCM-A
//   part 1  0x30-0xFF  FM 4-6           part 1  0x30-0xFF  FM 4-6
//
// (jt12_mmr.v:342-391: `if(part && selected_register[7:6]==2'b0)` is ADPCM-A,
// `if(!part && selected_register[7:4]==4'h1)` is ADPCM-B.) So every guest
// write is re-addressed before it reaches jt12, and a couple of them are
// dropped because forwarding them would land on the wrong block.
//
// RHYTHM: WHY jt12's ADPCM-A IS THE RIGHT ENGINE EVEN THOUGH THE SAMPLES ARE
// WAVs. The YM2608's rhythm section IS an ADPCM-A block with its sample ROM on
// the die, and the register semantics survive the move between the two chips
// unchanged:
//   YM2608 0x10  KON/dump: bit7 dump, bits 5:0 channel mask
//   YM2610 0x100 aon_cmd : bit7 dump, bits 5:0 channel mask   (jt10_adpcm_drvA.v:80)
//   YM2608 0x11  total level, 6 bits      == YM2610 0x101 atl
//   YM2608 0x18-0x1D {L,R,xx,IL[4:0]}     == YM2610 0x108-0x10D LRACL
// The only thing the YM2610 has extra is the per-channel start/end address
// pair (0x110-0x12D), because its samples are off-die. That is exactly the
// hook this core needs: the firmware writes the six start/end pairs once at
// boot, and from then on the guest's rhythm writes drive a real ADPCM-A block
// with correct per-channel pan, per-channel level, total level, end flags and
// playback rate -- for zero extra ALM, since use_adpcm=1 was already paid for
// to get the stereo jt10_acc accumulator and ADPCM-B.
//
// The cost is that the samples have to BE ADPCM-A. np2kai loads them as WAVs
// (sound/rhythmc.c:11-20: 2608_bd/sd/top/hh/tom/rim.wav, via pcmmix_regfile),
// so the firmware transcodes WAV -> YM ADPCM-A on the way in. That is
// command-rate work and belongs beside fdd_service.c / scsi_service.c, not
// here. A bespoke six-voice PCM player in RTL was the alternative and it is
// strictly worse: more ALM, more block RAM (16-bit PCM instead of 4-bit
// ADPCM), and every one of np2's mixing rules re-implemented by hand.
//
// The buffer below is therefore an ADPCM-A sample store, not a PCM one, and
// jt10_adpcm_cnt.v:106-107 addresses it in units of 256 bytes
// (addr1[20:9] is the 12-bit start/end register), so RHY_BYTES must be a
// multiple of 256.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//

`default_nettype none

module pc98_opna #(
    // ADPCM-A rhythm sample store, firmware-filled. 8 KB is 8 M10K out of the
    // ~111 the PC-98 fit leaves free, and 32 units of the 256-byte granularity
    // the ADPCM-A start/end registers work in.
    parameter int RHY_BYTES = 8192,
    parameter int RHY_AW    = 13,
    // clk / 7.9872 MHz as a 16-bit fraction -- see the header.
    parameter int CEN_INC   = 12185
) (
    input  wire        clk,             // clk_chipset, 42.954545 MHz
    input  wire        rst,

    // ---- guest side -------------------------------------------------------
    // cs is the decode for 0x188-0x18F; a2a1 is address[2:1], so
    //   00 -> 0x188   01 -> 0x18A   10 -> 0x18C   11 -> 0x18E
    // (address[0] is part of the decode: the odd addresses are not the board).
    input  wire        cs,
    input  wire  [1:0] a2a1,
    input  wire        io_read_n,
    input  wire        io_write_n,
    input  wire  [7:0] data_in,
    output logic [7:0] data_out,
    output wire        read_select,

    // Bit 0 of the last write to 0xA460 (np2kai cbus/pcm86io.c:45-51). Low
    // means the board answers as a 3-channel mono OPN and 0x18C/0x18E are open
    // bus; high is the 6-channel stereo OPNA every PC-98 FM driver wants.
    input  wire        ext_enable,

    output wire        irq,             // active high, INT5 on the -86 board

    // ---- softcore side ----------------------------------------------------
    // The firmware's window, addressed like pc98_scsi's: an index port and an
    // auto-incrementing data port for the bulk path, plus two register-inject
    // ports for the one-off setup writes.
    //   0 W: rhythm store address (RHY_AW bits), absolute
    //   1 W: rhythm store data byte, post-increments the address
    //   2 W: inject {reg[7:0], data[7:0]} into jt12 part 0
    //   3 W: inject {reg[7:0], data[7:0]} into jt12 part 1
    //   4 R: {15'd0, router busy}
    input  wire  [3:0] mg_reg,
    input  wire        mg_wr,
    input  wire [15:0] mg_wdata,
    output logic [15:0] mg_rdata,

    // ---- ADPCM-B (DELTA-T) memory ----------------------------------------
    // The -86 board carries 256 KB of ADPCM RAM. That does not fit in block
    // RAM, so this is brought out for a fourth sdram_mp.sv port. Until that
    // exists the caller ties adpcmb_data low and the DELTA-T channel is silent;
    // nothing else in the chip depends on it.
    output wire [23:0] adpcmb_addr,
    output wire        adpcmb_roe_n,
    input  wire  [7:0] adpcmb_data,

    // ---- audio ------------------------------------------------------------
    output wire signed [15:0] snd_l,
    output wire signed [15:0] snd_r
);

    // ------------------------------------------------------------------
    // Chip clock enable
    // ------------------------------------------------------------------
    logic [16:0] cen_acc;
    wire         cen = cen_acc[16];
    always_ff @(posedge clk) begin
        if (rst) cen_acc <= 17'd0;
        else     cen_acc <= {1'b0, cen_acc[15:0]} + 17'(CEN_INC);
    end

    // ------------------------------------------------------------------
    // Guest bus: commit on the trailing edge of the strobe
    // ------------------------------------------------------------------
    // Same hazard pc98_scsi.sv is written around: the address bus is still
    // moving at the start of an I/O cycle, so the port is latched while the
    // strobe is low and the write is committed when it lifts.
    wire wr = cs & ~io_write_n;
    wire rd = cs & ~io_read_n;

    logic       wr_q;
    logic [7:0] wr_data_q;
    logic [1:0] wr_port_q;
    logic [1:0] rd_port_q;

    always_ff @(posedge clk) begin
        wr_q <= wr;
        if (wr) begin
            wr_data_q <= data_in;
            wr_port_q <= a2a1;
        end
        if (rd) rd_port_q <= a2a1;
    end

    wire wr_commit = wr_q & ~wr;

    // The two register-index latches (np2kai board86.c:17-41: opna_o188 sets
    // s.addrl, opna_o18c sets s.addrh and only when s.extend).
    logic [7:0] addrl, addrh;
    logic [7:0] data_latch;      // np2 keeps s.data as the last byte written,
                                 // and returns it from the data ports for
                                 // every register that is not readable.

    // ------------------------------------------------------------------
    // The router
    // ------------------------------------------------------------------
    // One guest register write becomes two jt12 bus beats: an address write
    // (addr[0]=0, din = register) and a data write (addr[0]=1, din = value),
    // because jt12_mmr latches `part` from addr[1] on the address beat
    // (jt12_mmr.v:271-273) and then refuses the data beat unless addr[1]
    // still matches (jt12_mmr.v:284).
    //
    // jt12_mmr's `write` is a level (`!cs_n && !wr_n`), so each beat is
    // exactly one clk wide; a held strobe would re-apply the same write every
    // cycle.
    logic       rq_pend;
    logic       rq_part;
    logic [7:0] rq_reg, rq_data;
    logic [1:0] rtr_state;       // 0 idle, 1 address beat, 2 data beat

    localparam logic [1:0] RTR_IDLE = 2'd0, RTR_ADDR = 2'd1, RTR_DATA = 2'd2;

    wire rtr_busy = rq_pend | (rtr_state != RTR_IDLE);

    // Rhythm shadow, readable by the firmware through mg_reg 7. jt12 has no
    // read-back for its ADPCM-A control registers and a YM2608 has none for
    // its rhythm ones either, so this exists only so the service loop can see
    // whether the guest is using rhythm at all before it spends time loading
    // samples.
    logic [7:0] rhy_kon;         // 0x10, {dump, xx, mask[5:0]}
    logic [5:0] rhy_tl;          // 0x11, total level

    // Decode a guest register write into the jt12 write it becomes.
    // `fwd` low means the write is deliberately dropped.
    function automatic logic route_fwd(input logic p, input logic [7:0] r);
        if (!p) begin
            // part 0: SSG, rhythm, timers, FM 1-3
            // 0x10-0x1F is rhythm on a YM2608 and ADPCM-B on jt12, so only the
            // registers that have an ADPCM-A twin are forwarded.
            if (r[7:4] == 4'h1)
                route_fwd = (r == 8'h10) || (r == 8'h11) ||
                            ((r >= 8'h18) && (r <= 8'h1D));
            else
                route_fwd = 1'b1;
        end else begin
            // part 1: DELTA-T, then FM 4-6. 0x0C/0x0D are the DELTA-T limit
            // registers and 0x08 is the CPU's data port into the board's
            // ADPCM RAM; jt12's drvB has neither, so they are dropped. See the
            // gap list at the foot of this file.
            if (r <= 8'h0B)      route_fwd = 1'b1;
            else if (r == 8'h10) route_fwd = 1'b1;   // flag control
            else if (r >= 8'h30) route_fwd = 1'b1;
            else                 route_fwd = 1'b0;
        end
    endfunction

    function automatic logic route_part(input logic p, input logic [7:0] r);
        // Rhythm crosses to jt12's part 1; DELTA-T crosses to its part 0.
        if (!p) route_part = (r[7:4] == 4'h1);
        else    route_part = (r >= 8'h30);
    endfunction

    function automatic logic [7:0] route_reg(input logic p, input logic [7:0] r);
        if (!p) begin
            // 0x10 -> 0x100 aon, 0x11 -> 0x101 atl, 0x18-0x1D -> 0x108-0x10D
            // lracl. The low nibble carries straight across in all three.
            route_reg = (r[7:4] == 4'h1) ? {4'h0, r[3:0]} : r;
        end else begin
            // DELTA-T 0x00-0x0B -> jt12 0x10-0x1B, and the YM2608 flag-control
            // register 0x110 -> jt12's 0x1C.
            if (r <= 8'h0B)      route_reg = 8'h10 + r;
            else if (r == 8'h10) route_reg = 8'h1C;
            else                 route_reg = r;
        end
    endfunction

    // ------------------------------------------------------------------
    // Guest writes
    // ------------------------------------------------------------------
    // np2kai board86.c:17-51 exactly: 0x188 sets addrl and s.data; 0x18A sets
    // s.data and writes the register; 0x18C/0x18E do the same for addrh but
    // only while extended.
    wire        gw_is_data = wr_port_q[0];
    wire        gw_part    = wr_port_q[1];
    wire [7:0]  gw_reg     = wr_port_q[1] ? addrh : addrl;
    wire        gw_allowed = ~wr_port_q[1] | ext_enable;

    always_ff @(posedge clk) begin
        if (rst) begin
            addrl      <= 8'h00;
            addrh      <= 8'h00;
            data_latch <= 8'h00;
            rq_pend    <= 1'b0;
            rq_part    <= 1'b0;
            rq_reg     <= 8'h00;
            rq_data    <= 8'h00;
            rhy_kon    <= 8'h00;
            rhy_tl     <= 6'h00;
        end else begin
            // The FSM consumes the request on the way out of idle; a new one
            // is only taken once that has happened. Two clk cycles at
            // 42.95 MHz is far inside one guest OUT, and status bit 7 reads
            // back busy for the whole of it (status0_out below), so a driver
            // that polls before writing can never see the window.
            if (rtr_state == RTR_IDLE && rq_pend)
                rq_pend <= 1'b0;

            if (wr_commit && gw_allowed) begin
                data_latch <= wr_data_q;
                if (!gw_is_data) begin
                    if (gw_part) addrh <= wr_data_q;
                    else         addrl <= wr_data_q;
                end else begin
                    if (!gw_part) begin
                        if (gw_reg == 8'h10) rhy_kon <= wr_data_q;
                        if (gw_reg == 8'h11) rhy_tl  <= wr_data_q[5:0];
                    end
                    if (route_fwd(gw_part, gw_reg) && !rtr_busy) begin
                        rq_pend <= 1'b1;
                        rq_part <= route_part(gw_part, gw_reg);
                        rq_reg  <= route_reg (gw_part, gw_reg);
                        rq_data <= wr_data_q;
                    end
                end
            end else if (mg_wr && (mg_reg == 4'd2 || mg_reg == 4'd3) && !rtr_busy) begin
                // The firmware's raw injection path. It is how the six
                // ADPCM-A start/end pairs (jt12 part 1, 0x110-0x12D) get
                // programmed after the rhythm store is filled -- registers the
                // router deliberately refuses to let the guest reach. The
                // firmware polls mg_reg 4 before each one.
                rq_pend <= 1'b1;
                rq_part <= (mg_reg == 4'd3);
                rq_reg  <= mg_wdata[15:8];
                rq_data <= mg_wdata[7:0];
            end
        end
    end

    // The FSM that turns rq_* into the two bus beats.
    logic       jt_cs_n, jt_wr_n;
    logic [1:0] jt_addr_w;
    logic [7:0] jt_din;

    always_ff @(posedge clk) begin
        if (rst) begin
            rtr_state <= RTR_IDLE;
        end else begin
            case (rtr_state)
                RTR_IDLE: if (rq_pend) rtr_state <= RTR_ADDR;
                RTR_ADDR:              rtr_state <= RTR_DATA;
                RTR_DATA:              rtr_state <= RTR_IDLE;
                default:               rtr_state <= RTR_IDLE;
            endcase
        end
    end

    always_comb begin
        jt_cs_n   = 1'b1;
        jt_wr_n   = 1'b1;
        jt_addr_w = 2'b00;
        jt_din    = 8'h00;
        case (rtr_state)
            RTR_ADDR: begin
                jt_cs_n   = 1'b0;
                jt_wr_n   = 1'b0;
                jt_addr_w = {rq_part, 1'b0};
                jt_din    = rq_reg;
            end
            RTR_DATA: begin
                jt_cs_n   = 1'b0;
                jt_wr_n   = 1'b0;
                jt_addr_w = {rq_part, 1'b1};
                jt_din    = rq_data;
            end
            default: ;
        endcase
    end

    // ------------------------------------------------------------------
    // Reading jt12: shadow all four dout views
    // ------------------------------------------------------------------
    // jt12_dout.v is a mux on `addr` registered one clk late, and this core
    // needs three of its four views at once (status 0 at 0x188, the SSG
    // read-back at 0x18A, status 1 at 0x18C). Parking `addr` on whichever port
    // the guest happens to be reading would couple jt12's read latency to the
    // guest's strobe width, so instead `addr` free-runs through all four
    // whenever the router is idle and each view is captured into a shadow.
    // Nothing is disturbed by this: `write` is `!cs_n && !wr_n`, so moving
    // `addr` with cs_n high cannot write anything.
    logic [1:0] rr_addr;
    logic [1:0] jt_addr_d;
    logic [7:0] jt_dout;
    logic [7:0] sh [0:3];

    wire [1:0] jt_addr = (rtr_state == RTR_IDLE) ? rr_addr : jt_addr_w;

    always_ff @(posedge clk) begin
        if (rst) begin
            rr_addr   <= 2'b00;
            jt_addr_d <= 2'b00;
        end else begin
            if (rtr_state == RTR_IDLE) rr_addr <= rr_addr + 2'd1;
            // jt12_dout registers dout <= f(addr), so the view presented on
            // cycle n is readable on cycle n+1: one delay stage lines the
            // capture up with the address that produced it.
            jt_addr_d <= jt_addr;
            sh[jt_addr_d] <= jt_dout;
        end
    end

    wire [7:0] status0 = sh[2'b00];   // {busy, 5'd0, flag_B, flag_A}
    wire [7:0] ssg_rd  = sh[2'b01];
    wire [7:0] status1 = sh[2'b10];   // {adpcmb_flag, 1'b0, adpcma_flags}

    // The router adds its own latency on top of jt12's busy, and a driver that
    // polls bit 7 and then writes immediately must not outrun it.
    wire [7:0] status0_out = {status0[7] | rtr_busy, status0[6:0]};

    assign read_select = rd;

    always_comb begin
        case (rd_port_q)
            2'b00: data_out = status0_out;
            // np2kai board86.c:56-78: 0x18A returns the SSG register for
            // index < 0x10, 0x01 for index 0xFF (the "is there a chip here"
            // probe), and the data latch otherwise. Index 0x0E is the joystick
            // port on a real board; nothing reads it here, and jt12's SSG
            // returns its own IOA which is tied high.
            2'b01: data_out = (addrl < 8'h10) ? ssg_rd
                            : (addrl == 8'hFF) ? 8'h01
                            : data_latch;
            // 0x18C/0x18E are open bus unless the board is extended
            // (board86.c:80-105).
            2'b10: data_out = ext_enable ? status1 : 8'hFF;
            2'b11: data_out = ext_enable ? data_latch : 8'hFF;
            default: data_out = 8'hFF;
        endcase
    end

    // ------------------------------------------------------------------
    // Softcore window
    // ------------------------------------------------------------------
    logic [RHY_AW-1:0] mg_rhy_addr;

    // The ADPCM-A rhythm store. Read by jt12 through adpcma_addr, written by
    // the firmware one byte at a time.
    (* ramstyle = "M10K" *) logic [7:0] rhy_mem [0:RHY_BYTES-1];
    logic [7:0] rhy_q;

    // adpcma_bank is the YM2610's extra ROM-select nibble and adpcma_roe_n its
    // ROM output enable; with the whole store inside the FPGA there is nothing
    // to select and nothing to enable, so both are left dangling on purpose.
    wire [19:0] adpcma_addr;
    wire [ 4:0] adpcma_bank;
    wire        adpcma_roe_n;

    always_ff @(posedge clk) begin
        if (mg_wr && (mg_reg == 4'd1)) rhy_mem[mg_rhy_addr] <= mg_wdata[7:0];
        rhy_q <= rhy_mem[adpcma_addr[RHY_AW-1:0]];
    end

    always_ff @(posedge clk) begin
        if (rst)
            mg_rhy_addr <= '0;
        else if (mg_wr && (mg_reg == 4'd0))
            mg_rhy_addr <= mg_wdata[RHY_AW-1:0];
        else if (mg_wr && (mg_reg == 4'd1))
            mg_rhy_addr <= mg_rhy_addr + 1'b1;
    end

    always_comb begin
        case (mg_reg)
            4'd4:    mg_rdata = {15'd0, rtr_busy};
            4'd5:    mg_rdata = {8'd0, status0};
            4'd6:    mg_rdata = {8'd0, status1};
            4'd7:    mg_rdata = {2'd0, rhy_tl, rhy_kon};
            default: mg_rdata = 16'h0000;
        endcase
    end

    // ------------------------------------------------------------------
    // The chip
    // ------------------------------------------------------------------
    // mask_div=0 matters: with the default 1, jt12_mmr.v:277 skips the
    // 0x2D/0x2E/0x2F prescaler decode, and those are live registers on a
    // YM2608 -- jt12_div.v:51-57 documents the mapping against the datasheet.
    // Its reset value, 2'b10 (FM 1/6, SSG 1/4), is the YM2608's.
    wire irq_n;
    wire signed [15:0] jt_snd_l, jt_snd_r;

    jt12_top #(
        .use_lfo   (1),
        .use_ssg   (1),
        .num_ch    (6),
        .use_pcm   (0),
        .use_adpcm (1),
        .mask_div  (0)
    ) u_opna (
        .rst          (rst),
        .clk          (clk),
        .cen          (cen),
        .din          (jt_din),
        .addr         (jt_addr),
        .cs_n         (jt_cs_n),
        .wr_n         (jt_wr_n),
        .dout         (jt_dout),
        .irq_n        (irq_n),
        .en_hifi_pcm  (1'b0),
        .adpcma_addr  (adpcma_addr),
        .adpcma_bank  (adpcma_bank),
        .adpcma_roe_n (adpcma_roe_n),
        .adpcma_data  (rhy_q),
        .adpcmb_addr  (adpcmb_addr),
        .adpcmb_roe_n (adpcmb_roe_n),
        .adpcmb_data  (adpcmb_data),
        .IOA_in       (8'hFF),
        .IOB_in       (8'hFF),
        .snd_left     (jt_snd_l),
        .snd_right    (jt_snd_r),
        .snd_sample   (),
        .ch_enable    (6'h3F),
        .debug_bus    (8'h00)
    );

    assign irq   = ~irq_n;
    assign snd_l = jt_snd_l;
    assign snd_r = jt_snd_r;

    // ------------------------------------------------------------------
    // KNOWN GAPS (nothing below is implemented yet)
    // ------------------------------------------------------------------
    //  * ADPCM-B has no memory. adpcmb_addr/adpcmb_data want a fourth
    //    sdram_mp.sv port (it is `parameter int PORTS = 3` today) and a
    //    256 KB window in pc98_sdram_map.svh.
    //  * ADPCM-B is read-only in jt12. On a real -86 the 256 KB is RAM and the
    //    guest fills it by writing register 0x108 with control1[6:5] == 2'b11
    //    (np2kai sound/adpcmc.c:85-89). That needs a write path into the same
    //    SDRAM window, which jt10_adpcm_drvB does not have; the DELTA-T limit
    //    registers 0x10C/0x10D have no jt12 equivalent either.
    //  * The rhythm store is empty until the firmware fills it. It needs a
    //    WAV -> YM ADPCM-A transcoder beside fdd_service.c, and six start/end
    //    pairs injected through mg_reg 3 afterwards.
    //  * There is no -86 16-bit PCM (0xA460-0xA46C, np2kai cbus/pcm86io.c).
    //    Only bit 0 of 0xA460 is decoded, because extended mode depends on it.

endmodule

`default_nettype wire
